### PR TITLE
Add link to `template` cli

### PR DESCRIPTION
**Pull request by vfonic**
Thanks for all the open source work you're doing! 🤘

### CODE REVIEW

**Comment by fabiospampinato** [comment]
I should definitely link to "template" in all my templates for it. I think I'll have to write a command for [autogit](https://github.com/fabiospampinato/autogit) for this, I'd like to keep those repositories consistent with each other 🤔

**Comment by vfonic** [comment]
I love autogit! I created something similar, but far feature incomplete than autogit :)

I don't know what command you would run to keep the repositories consistent, but let me suggest a crazy one:
```sh
git fetch https://github.com/vfonic/template-vscode-extension.git patch-1
git cherry-pick 1f98fd77af7a870b08b029d0fed834ab3a79a6ee
```
(fetch whatever repo you want with the existing commit, cherry-pick the specific commit with the changes you want to see in this project - of course, this would only work if there's nothing project-specific in the changes, like project name etc.)

**Comment by fabiospampinato** [comment]
🤔 interesting, I've actually never used "cherry-pick", I should definitely learn more about this.

**Comment by fabiospampinato** [comment]
I've implemented this right now, thanks for the suggestion! In the end I didn't merge this PR because I've worded the thing slightly differently.

**Comment by vfonic** [comment]
Sounds good to me! 🤘

**Pull request closed without merging**
